### ISSUE TITLE
An issue with plate solve

### ISSUE THREAD

**Issue by karolbe** [rlancaste/stellarsolver#73]
Hello!
I have posted a message on EKOS forum on indilib.org describing my problems with plate solving. I am not sure if you (the authors) read the forum, so decided to create an issue here.

Basically, the problem is that while in many cases StellarSolver solves images just fine, there are cases where it fails and I do not see explanation.

Lets take the attached Rosette Nebula image, when I resolve the image it fails:

Automatically downsampling the image by 3
Evaluating Installed RAM for inParallel Option.  Total Size of Index files: 1.96174 GB, Installed RAM: 62.7147 GB, Free RAM: 5.21823 GB
There should be enough RAM to load the indexes in parallel.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Sextractor with the 1-Default profile . . .
Stars Found before Filtering: 509
Stars Found after Filtering: 509
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Configuring StellarSolver
Scale range: 13.3125 to 16.2709 arcsec/pixel
Downsampling is multiplying the pixel scale by: 3
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Solver was aborted, timed out, or failed, so no solution was found
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Internal Extractor w/ StellarSolver failed after 591.048 second(s).
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Interestingly, when I un-check "Use Scale" (which by default is set to Low: 4.43751 and High: 5.42363) it gets solved immediately. I suspect that when I use KStars/EKOS to plate solve, it sets the Scale values and it is causing the issue, I have unchecked the scale options in EKOS settings but this does not make any difference:

![image](https://user-images.githubusercontent.com/1939578/104843492-3a9e7280-58cb-11eb-947e-f2263948c50d.png)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Automatically downsampling the image by 3
Evaluating Installed RAM for inParallel Option.  Total Size of Index files: 1.96174 GB, Installed RAM: 62.7147 GB, Free RAM: 21.3926 GB
There should be enough RAM to load the indexes in parallel.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Sextractor with the 1-Default profile . . .
Stars Found before Filtering: 508
Stars Found after Filtering: 508
Starting 24 threads to solve on multiple scales
Solver # 1, Low 0.1, High 0.412326 arcsecperpix
Solver # 2, Low 0.412326, High 1.34931 arcsecperpix
Solver # 3, Low 1.34931, High 2.91094 arcsecperpix
Solver # 4, Low 2.91094, High 5.09722 arcsecperpix
Solver # 5, Low 5.09722, High 7.90816 arcsecperpix
Solver # 6, Low 7.90816, High 11.3438 arcsecperpix
Solver # 7, Low 11.3438, High 15.404 arcsecperpix
Solver # 8, Low 15.404, High 20.0889 arcsecperpix
Solver # 9, Low 20.0889, High 25.3984 arcsecperpix
Solver # 10, Low 25.3984, High 31.3326 arcsecperpix
Solver # 11, Low 31.3326, High 37.8915 arcsecperpix
Solver # 12, Low 37.8915, High 45.075 arcsecperpix
Solver # 13, Low 45.075, High 52.8832 arcsecperpix
Solver # 14, Low 52.8832, High 61.316 arcsecperpix
Solver # 15, Low 61.316, High 70.3734 arcsecperpix
Solver # 16, Low 70.3734, High 80.0556 arcsecperpix
Solver # 17, Low 80.0556, High 90.3623 arcsecperpix
Solver # 18, Low 90.3623, High 101.294 arcsecperpix
Solver # 19, Low 101.294, High 112.85 arcsecperpix
Solver # 20, Low 112.85, High 125.031 arcsecperpix
Solver # 21, Low 125.031, High 137.836 arcsecperpix
Solver # 22, Low 137.836, High 151.266 arcsecperpix
Solver # 23, Low 151.266, High 165.321 arcsecperpix
Solver # 24, Low 165.321, High 180 arcsecperpix
Scale range: 0.1 to 0.412326 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 0.218447 to 0.900713
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 15.404 to 20.0889 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 33.6495 to 43.8835
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 45.075 to 52.8832 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 98.4648 to 115.521
Scale range: 52.8832 to 61.316 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 115.521 to 133.943
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 112.85 to 125.031 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 246.517 to 273.125
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 101.294 to 112.85 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 221.273 to 246.517
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 25.3984 to 31.3326 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 55.482 to 68.4451
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 151.266 to 165.321 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 330.435 to 361.137
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 125.031 to 137.836 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 273.125 to 301.098
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 137.836 to 151.266 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 301.098 to 330.435
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 1.34931 to 2.91094 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 2.94751 to 6.35884
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 20.0889 to 25.3984 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 43.8835 to 55.482
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 61.316 to 70.3734 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 133.943 to 153.728
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 11.3438 to 15.404 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 24.78 to 33.6495
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 165.321 to 180 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 361.137 to 393.204
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 2.91094 to 5.09722 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 6.35884 to 11.1347
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 7.90816 to 11.3438 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 17.2751 to 24.78
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 5.09722 to 7.90816 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 11.1347 to 17.2751
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 37.8915 to 45.075 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 82.7727 to 98.4648
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 70.3734 to 80.0556 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 153.728 to 174.879
Scale range: 0.412326 to 1.34931 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 0.900713 to 2.94751
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 80.0556 to 90.3623 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 174.879 to 197.393
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 90.3623 to 101.294 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 197.393 to 221.273
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 31.3326 to 37.8915 degrees wide
Image width: 4944 pixels, Downsampled Image width: 1648 pixels; arcsec per pixel range: 68.4451 to 82.7727
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Solve Log Odds:  155.568
Number of Matches:  22
Solved with index:  4111
Field center: (RA,Dec) = (97.9495, 4.9492) deg.
Field center: (RA H:M:S, Dec D:M:S) = (06:31:47.870, +04:56:57.124).
Field is: (-14.7958, -9.18354) deg from search coords.
Field size: 3.05834 x 2.03064 degrees
Pixel Scale: 2.22755"
Field rotation angle: up is 78.6137 degrees E of N
Field parity: neg

You can find more test images (which fail and succeed), including the Rosetta one, here: https://drive.google.com/drive/folders/1S7Mn9SVHWSAEA8Cn5O0KCPFPdfGlnJaQ?usp=sharing

[Rosetta_Light_300_secs_2020-12-04T23-27-54_001.zip](https://github.com/rlancaste/stellarsolver/files/5826089/Rosetta_Light_300_secs_2020-12-04T23-27-54_001.zip)

**Comment by rlancaste** [comment]
Hi there, I just posted an answer in the INDIlib forum.  I am one of the folks that actively works on KStars.  I made stellarsolver based on astrometry.net in order to create a plate solver that would work better for KStars on different systems.

**Comment by rlancaste** [comment]
The issue you posted doesn't appear to be an issue with StellarSolver.  It might be an issue with KStars, but I'm not sure that is the case. Please check my response on INDILib.  I analyzed each image and in each case it was a different issue.

**Comment by karolbe** [comment]
Thank you very much for quick response. I will check my set up in KStars to see where this discrepancy may come from.

**Comment by rlancaste** [comment]
Yeah, as I said in the Forum, it could be a KStars bug, but I think the Rosette's scale error may have come from something being wrong in the initial scale KStars was using to plate solve when you started up.  I think the second image, maybe you had moved to the object and then restarted or reconnected so that KStars thought it was pointing at the pole but really you were not.  And I don't understand the other 2 as I said.

**Comment by jochym** [comment]
I have similar problems with stellarsolver. While it is *much* faster than standard astrometry solver it is also (unfortunately) much less effective. And this is not a problem with kstars/ekos. I have images which got solved by in "local astrometry" in SS Tester without any problem but cannot be solved by SS (or I cannot make it solve). Examples here: https://drive.google.com/file/d/1wTmqG0PaeEd1J5liMyGL444s9-_3oPhm/view?usp=sharing
These images are bad - this is not a point. The point is the local astrometry solves them without any problems. I really hope I am doing something wrong because kstars/ekos just got much less good at alignment since the stellar solver an only option. 
BTW: is there a way to switch to local astrometry solver in SS in EKOS? That would help work around this problem.

**Comment by rlancaste** [comment]
Hi, remember that Stellarsolver has the ability to use local astrometry.  You don't have to use the built in solver.  In the options, you can select to use the "built in" star extractor and the "local astrometry" solver and you are using local astrometry exactly as it was previously.

**Comment by rlancaste** [comment]
Also note that if the image does solve with the Stellar Solver tester, but does not solve with KStars using the settings that you selected, then there could be an issue either with settings in KStars or maybe something with the kstars code that uses StellarSolver to solve images

**Comment by rlancaste** [comment]
If you need to see how to switch to using local astrometry:

<img width="744" alt="Screen Shot 2021-02-28 at 3 46 19 PM" src="https://user-images.githubusercontent.com/19987848/109433043-4e65ea00-79dc-11eb-8a00-7c1d9d212291.png">

**Comment by jochym** [comment]
Thanks! I have missed these settings.
The issue I have reported above is checked in StellarSolver Tester *not* kstars.

**Comment by rlancaste** [comment]
oh ok I see.  If they don't solve, I would assume that the issue could be related to the star extraction settings.  I will check your examples and see what's up.

**Comment by rlancaste** [comment]
I just ran a quick test of the M44 image you shared.  It solved in my StellarSolver tester in about 3 seconds accurately using the internal solver and the Small Scale Solving Profile which is the one I recommend as a default solving profile.  I also tried with local astrometry and its own star extraction using StellarSolver and it solved in about 10 seconds due to the parallel threads.

The Internal Solver:

Solved with index:  4207
Field center: (RA,Dec) = (130.183, 19.5993) deg.
Field center: (RA H:M:S, Dec D:M:S) = (08:40:43.887, +19:35:57.448).
Field size: 55.866 x 37.2094 arcminutes
Pixel Scale: 0.857881"
Field rotation angle: up is 39.7876 degrees E of N
Field parity: pos

Successfully solved with child solver: 5
Shutting down other child solvers
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Internal Extractor w/ StellarSolver  took a total of: 3.286 second(s).
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by rlancaste** [comment]
The positions agreed between the two methods to within an arc second.  08:40:43.887 vs. 08:40:43.697 and +19:35:57.448 vs. +19:35:58.848

I am not sure I see an issue with that example.

**Comment by rlancaste** [comment]
Can you share more about why this image didn't solve on your system?

**Comment by jochym** [comment]
The positions are not an issue. In my tests I used the same set of positions for both solvers (did not change first selector in the tester just the second). 
I re-tested the m44 - I cannot make the internal solver solve at any settings. 
Local astrometry solves using default (1) profile in 1.5s 
I am probably doing something wrong - could you point me to the procedure I should use for this test to be valid? It seems we get different results on the same image (admittedly a difficult one). The code is freshly compiled from git. This is on debian 10. I'll be happy to share any config info you need to identify the root of the problem. The main difference I can spot is a large discrepancy in number of detected stars in both runs - despite claiming the same extractor with the same profile. Here is the log of the test run on m44 image (first internal solver, then local astrometry):
```
Automatically downsampling the image by 2
Evaluating Installed RAM for inParallel Option.  Total Size of Index files: 2.20994 GB, Installed RAM: 31.2858 GB, Free RAM: 5.52428 GB
There should be enough RAM to load the indexes in parallel.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Sextractor with the 1-Default profile . . .
Stars Found before Filtering: 72
Stars Found after Filtering: 72
Starting 4 threads to solve on multiple scales
Solver # 1, Low 0.1, High 11.3438 arcminwidth
Solver # 2, Low 11.3438, High 45.075 arcminwidth
Solver # 3, Low 45.075, High 101.294 arcminwidth
Solver # 4, Low 101.294, High 180 arcminwidth
Scale range: 45.075 to 101.294 degrees wide
Image width: 3908 pixels, Downsampled Image width: 1954 pixels; arcsec per pixel range: 83.045 to 186.621
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Child solver: 3 did not solve or was aborted
Scale range: 11.3438 to 45.075 degrees wide
Image width: 3908 pixels, Downsampled Image width: 1954 pixels; arcsec per pixel range: 20.8994 to 83.045
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 0.1 to 11.3438 degrees wide
Image width: 3908 pixels, Downsampled Image width: 1954 pixels; arcsec per pixel range: 0.184237 to 20.8994
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Scale range: 101.294 to 180 degrees wide
Image width: 3908 pixels, Downsampled Image width: 1954 pixels; arcsec per pixel range: 186.621 to 331.627
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine with the 1-Default profile. . .
Child solver: 2 did not solve or was aborted
Child solver: 1 did not solve or was aborted
Child solver: 4 did not solve or was aborted
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Internal Extractor w/ StellarSolver failed after 0.324 second(s).
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Automatically downsampling the image by 2
Evaluating Installed RAM for inParallel Option.  Total Size of Index files: 2.20994 GB, Installed RAM: 31.2858 GB, Free RAM: 5.5914 GB
There should be enough RAM to load the indexes in parallel.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Sextractor with the 1-Default profile . . .
Stars Found before Filtering: 388
Stars Found after Filtering: 388
Starting 4 threads to solve on multiple scales
Solver # 1, Low 0.1, High 11.3438 arcminwidth
Solver # 2, Low 11.3438, High 45.075 arcminwidth
Solver # 3, Low 45.075, High 101.294 arcminwidth
Solver # 4, Low 101.294, High 180 arcminwidth
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Configuring external Astrometry.net solver using an xylist input
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Configuring external Astrometry.net solver using an xylist input
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Configuring external Astrometry.net solver using an xylist input
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting external Astrometry.net solver with the 1-Default profile...
Command: /usr/bin/solve-field -O --no-plots --no-verify --crpix-center --match none --corr none --new-fits none --rdls none --resort --odds-to-solve 1e+09 --odds-to-tune-up 1e+06 -L 45.075 -H 101.294 -u degwidth --width 3908 --height 2602 --x-column X_IMAGE --y-column Y_IMAGE --sort-column MAG_AUTO --sort-ascending --no-remove-lines --uniformize 0 --backend-config /tmp/externalSextractorSolver_93_2.cfg --cancel /tmp/externalSextractorSolver_93_2.cancel -W /tmp/externalSextractorSolver_93_2.wcs /tmp/externalSextractorSolver_93_2.xyls
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting external Astrometry.net solver with the 1-Default profile...
Command: /usr/bin/solve-field -O --no-plots --no-verify --crpix-center --match none --corr none --new-fits none --rdls none --resort --odds-to-solve 1e+09 --odds-to-tune-up 1e+06 -L 0.1 -H 11.3438 -u degwidth --width 3908 --height 2602 --x-column X_IMAGE --y-column Y_IMAGE --sort-column MAG_AUTO --sort-ascending --no-remove-lines --uniformize 0 --backend-config /tmp/externalSextractorSolver_93_0.cfg --cancel /tmp/externalSextractorSolver_93_0.cancel -W /tmp/externalSextractorSolver_93_0.wcs /tmp/externalSextractorSolver_93_0.xyls
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Configuring external Astrometry.net solver using an xylist input
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting external Astrometry.net solver with the 1-Default profile...
Command: /usr/bin/solve-field -O --no-plots --no-verify --crpix-center --match none --corr none --new-fits none --rdls none --resort --odds-to-solve 1e+09 --odds-to-tune-up 1e+06 -L 101.294 -H 180 -u degwidth --width 3908 --height 2602 --x-column X_IMAGE --y-column Y_IMAGE --sort-column MAG_AUTO --sort-ascending --no-remove-lines --uniformize 0 --backend-config /tmp/externalSextractorSolver_93_3.cfg --cancel /tmp/externalSextractorSolver_93_3.cancel -W /tmp/externalSextractorSolver_93_3.wcs /tmp/externalSextractorSolver_93_3.xyls
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting external Astrometry.net solver with the 1-Default profile...
Command: /usr/bin/solve-field -O --no-plots --no-verify --crpix-center --match none --corr none --new-fits none --rdls none --resort --odds-to-solve 1e+09 --odds-to-tune-up 1e+06 -L 11.3438 -H 45.075 -u degwidth --width 3908 --height 2602 --x-column X_IMAGE --y-column Y_IMAGE --sort-column MAG_AUTO --sort-ascending --no-remove-lines --uniformize 0 --backend-config /tmp/externalSextractorSolver_93_1.cfg --cancel /tmp/externalSextractorSolver_93_1.cancel -W /tmp/externalSextractorSolver_93_1.wcs /tmp/externalSextractorSolver_93_1.xyls
Solution file doesn't exist
Child solver: 4 did not solve or was aborted
Loading WCS from file...
Finished Loading WCS...
Successfully solved with child solver: 1
Shutting down other child solvers
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Internal Extractor w/ local solver  took a total of: 1.516 second(s).
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by rlancaste** [comment]
One thing jumps out at me right away.  You are using the “1 default” profile, which I don’t recommend for plate solving.  Please try the one that I stated above. “4 parallel small scale”. It is a profile optimized for plate solving images from small scale telescopes.

**Comment by rlancaste** [comment]
There are a lot of settings in astrometry and SEP.  I have been working to develop profiles to optimize the settings and to make them work better for certain tasks.  The original or “default” settings are NOT optimized for this task

**Comment by jochym** [comment]
I understand that this is not optimal (default). The problem is that on your system you got solutions for both, but I did not. In truth local astrometry also solves only for default profile.
What worries me is the difference in behaviour for you and me.
With the m3 image which is better quality (slightly) the difference is even stronger.
Astrometry solves in all profiles except BigStars, Internal for none of them (including small scale).

Am I missing index files (I believe I do not, but I may be wrong)?
In /usr/share/astrometry I have index-2mass-03-xx.fits (xx=23-47) 
In .local/share/kstars/astrometry/ I have index-X.fits, X=4107-4113, 4208-4213, 4206-{00-11} 4207-{00-11}

**Comment by jochym** [comment]
@rlancaste Maybe the problem is running from the build directory?
I have built SST by running in the build directory:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTER=ON $srcdir
make
```

**Comment by rlancaste** [comment]
Here are the index files that I have.  I don't have the 2mass images

<img width="513" alt="Screen Shot 2021-03-02 at 9 18 48 PM" src="https://user-images.githubusercontent.com/19987848/109742428-004c1480-7b9d-11eb-9b5f-9c44d8b89890.png">

**Comment by rlancaste** [comment]
Sorry to clarify what I just said, I do have the 2mass images as in the 4200 series images I have checked here.  I don't have any files named index-2mass-03-xx.fits as you said.

**Comment by rlancaste** [comment]
for astrometry, were you using the SEP star extraction or were you using the built in astrometry star extraction?  If it solved for local astrometry using built in star extraction, but didn't solve using SEP, it could be that the star extraction was the problem.

**Comment by jochym** [comment]
I'll switch to kstars downloaded files for next test. The star extraction could be a problem since both logs report different number of stars despite the same setting in star extraction field. I will re-test and report. Thanks @rlancaste for working on this issue. The faster solver was really needed in kstars.

**Comment by nouspiro** [comment]
I encountered same issue. Could solve in kstars/ekos but without luck in stellarsolvertester. There is issue in LC_NUMERIC environment variable. Mine locale use comma as decimal separator. export LC_NUMERIC=C make it work.

I assume that somewhere in code decimal numbers are passed as strings which then contains comma as decimal separator.

Please add setlocale(LC_NUMERIC, "C") somewhere at start of tester app so it work.

**Comment by nouspiro** [comment]
From https://doc.qt.io/qt-5/qcoreapplication.html#locale-settings
QApplication app(argc, argv);
setlocale(LC_NUMERIC, "C");
